### ISSUE TITLE
Add tests for BrainFlow Streamer to Networking Test Kit

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#1100]
## **Is your feature request related to a problem? Please describe.**
These features are not documented well and have been included for some time. Discovered while writing QA tests for the GUI.

## **Describe the solution you'd like**
Inbound and outbound BrainFlow streaming are really cool features. Let's add some tests to the Networking Test Kit in this repository.

## **Describe alternatives you've considered**
More people could be using these features if they were tested more and documented properly.

## **Additional context**
N/A

**Comment by retiutut** [comment]
Discovered errors instantiating a Streaming board in the GUI (data coming in from an external source). Outbound seems to work fine.

```
CP: Playback History Size = 1
[DEFAULT]: Attempting to Start Session...
initButtonPressed: Calling initSystem() after next draw()
OpenBCI_GUI: Start session. Calling initSystem().


=================================================
||             INITIALIZING SYSTEM             ||
=================================================

OpenBCI_GUI: Init session using Streaming data source
[ERROR]: ERROR: brainflow.BrainFlowError: need to set master board attribute in BrainFlowInputParams:INVALID_ARGUMENTS_ERROR when initializing Brainflow board. Data will not stream.
brainflow.BrainFlowError: need to set master board attribute in BrainFlowInputParams:INVALID_ARGUMENTS_ERROR
	at brainflow.BoardShim.<init>(BoardShim.java:1319)
	at OpenBCI_GUI$BoardBrainFlowStreaming.initializeInternal(OpenBCI_GUI.java:2486)
	at OpenBCI_GUI$Board.initialize(OpenBCI_GUI.java:2312)
	at OpenBCI_GUI.initSystem(OpenBCI_GUI.java:763)
	at OpenBCI_GUI.systemInitSession(OpenBCI_GUI.java:1100)
	at OpenBCI_GUI.draw(OpenBCI_GUI.java:647)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
OpenBCI_GUI: Channel count set to 16
openBCI_GUI: haltSystem: Halting system for reconfiguration of settings...
brainflow.BrainFlowError: Error in release:CLASSIFIER_IS_NOT_PREPARED_ERROR
	at brainflow.MLModel.release(MLModel.java:228)
	at OpenBCI_GUI$W_Focus.endSession(OpenBCI_GUI.java:22810)
	at OpenBCI_GUI.haltSystem(OpenBCI_GUI.java:971)
	at OpenBCI_GUI.initSystem(OpenBCI_GUI.java:825)
	at OpenBCI_GUI.systemInitSession(OpenBCI_GUI.java:1100)
	at OpenBCI_GUI.draw(OpenBCI_GUI.java:647)
	at processing.core.PApplet.handleDraw(PApplet.java:2475)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
[DEFAULT]: Data stream is already stopped.
[ERROR]: Failed to initialize board. Please check that the board is on and has power. See Console Log for more details.
CP: Playback History Size = 1
ConsoleLog: Console closed!
ConsoleLog: Opening console log as text file!
```
