### ISSUE TITLE
open bci gui: java.net.ConnectException at start

### ISSUE THREAD

**Issue by dpjh1983** [OpenBCI/OpenBCI_GUI#380]
## Problem
open bci gui does not start / crashes at start.

Explain the problem
throws
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at processing.net.Client.<init>(Unknown Source)
	at OpenBCI_GUI$Hub.startTCPClient(OpenBCI_GUI.java:13105)
	at OpenBCI_GUI$Hub.<init>(OpenBCI_GUI.java:13081)
	at OpenBCI_GUI.systemUpdate(OpenBCI_GUI.java:1203)
	at OpenBCI_GUI.draw(OpenBCI_GUI.java:563)
	at processing.core.PApplet.handleDraw(PApplet.java:2429)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Instantiating hub object...

## Operating System and Version
Lubuntu 18.04 64 bit
i use the csr dongle shipped with the board.

## GUI Version
3.4

## Running standalone app
Are you running the downloaded app or are you running from Processing 3
error occurs in standanlone and via processing

## Type of OpenBCI Board
ganglion

## Are you using a WiFi Shield?
no
Yes/No

**Comment by daniellasry** [comment]
@dpjh1983 please let us know if this still happens in v4.1.2 beta. It's working for me in ubuntu ubuntu 18.04
