### ISSUE TITLE
Analog Read JSON error

### ISSUE THREAD

**Issue by retiutut** [OpenBCI/OpenBCI_GUI#414]
## Problem

When trying to run Analog Read, an error is produced to console and data is not fed to the Analog Read graphs properly:

```
{
  "auxData": {
    "data": [
      1,
      100,
      1,
      8,
      2,
      149
    ],
    "type": "Buffer"
  },
  "valid": true,
  "boardTime": 0,
  "_count": 841,
  "code": 204,
  "stopByte": 193,
  "startByte": 160,
  "channelDataCounts": [
    -7963682,
    -7957077,
    -7965214,
    -7963356,
    -7963931,
    -7965679,
    -7966990,
    -7968131
  ],
  "type": "data",
  "sampleNumber": 73,
  "timestamp": 1544031072815
}
Hub: parseMessage: error: java.lang.RuntimeException: JSONObject["auxData"] is not a JSONArray.
openBCI_GUI: stopButton was pressed...stopping data transfer...
OpenBCI_GUI: stopRunning: stop running...
Cyton: startDataTransfer(): writing 's' to the serial port...
Hub: sendCommand(char): sending 's'
Hub: processCommand: success -- 101692
java.lang.RuntimeException: JSONObject["auxData"] is not a JSONArray.
	at processing.data.JSONObject.getJSONArray(JSONObject.java:805)
	at OpenBCI_GUI$Hub.processData(OpenBCI_GUI.java:13408)
	at OpenBCI_GUI$Hub.parseMessage(OpenBCI_GUI.java:13123)
	at OpenBCI_GUI.clientEvent(OpenBCI_GUI.java:12807)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at processing.net.Client.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```
etc...

## Expected 

Display data from aux pins in the Analog Read widget with no errors.

## Operating System and Version

macOS and Windows

## GUI Version

4.0.3-dev

## Running standalone app

Processing

## Type of OpenBCI Board

Cyton and Cyton+Daisy

## Are you using a WiFi Shield?

No

**Comment by retiutut** [comment]
Testing...
