### ISSUE TITLE
[USABILITY] When the HUB is not running, the GUI should print a message telling you so, instead of an exception

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#432]
## Problem

If the HUB is not running, the GUI throws an exception and vomits:
```
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Instantiating hub object...     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at processing.net.Client.<init>(Unknown Source)
        at OpenBCI_GUI$Hub.startTCPClient(OpenBCI_GUI.java:13088)
        at OpenBCI_GUI$Hub.<init>(OpenBCI_GUI.java:13064)
        at OpenBCI_GUI.systemUpdate(OpenBCI_GUI.java:1243)
        at OpenBCI_GUI.draw(OpenBCI_GUI.java:608)
        at processing.core.PApplet.handleDraw(PApplet.java:2476)
        at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.util.TimerThread.mainLoop(Timer.java:555)
```

## Expected 

In a perfect world, the GUI could print:
`WARNING: Failed to connect to OpenBCIHub background application. LIVE functionality will be disabled. Is the HUB running?`

## Operating System and Version

macOS/Windows/Linux

## GUI Version

As of v4.0.4

**Comment by daniellasry** [comment]
I'll tackle this
