### ISSUE TITLE
InvocationTargetException when clicking on an empty BLE Devices list

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/OpenBCI_GUI#480]
## Problem
If you click inside the BLE Device list you'll get:

```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
        at controlP5.ControlBroadcaster.broadcast(Unknown Source)
        at controlP5.Controller.broadcast(Unknown Source)
        at controlP5.Controller.setValue(Unknown Source)
        at OpenBCI_GUI$MenuList.onClick(OpenBCI_GUI.java:6422)
        at controlP5.Controller.setMousePressed(Unknown Source)
        at controlP5.ControllerGroup.setMousePressed(Unknown Source)
        at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
        at controlP5.ControlWindow.mouseEvent(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1432)
        at processing.core.PApplet.handleMethods(PApplet.java:1634)
        at processing.core.PApplet.handleMouseEvent(PApplet.java:2742)
        at processing.core.PApplet.dequeueEvents(PApplet.java:2645)
        at processing.core.PApplet.handleDraw(PApplet.java:2486)
        at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:866)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
        at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
        at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
        at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
        at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
        at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at OpenBCI_GUI$MenuList.getItem(OpenBCI_GUI.java:6472)
        at OpenBCI_GUI.controlEvent(OpenBCI_GUI.java:3349)
        ... 33 more
```

## Operating System and Version
Windows 10

![Capture](https://user-images.githubusercontent.com/412426/55928433-76bc8380-5bcd-11e9-96bd-bcce9b8e20cd.PNG)

**Comment by retiutut** [comment]
@daniellasry Including this in 4.1.2-beta.0 PR. Should be fixed!
