### ISSUE TITLE
Can't connect to BLE on linux

### ISSUE THREAD

**Issue by kenmcneill** [OpenBCI/OpenBCI_GUI#965]
## Problem

Error on reading dongle, doesn't matter if USB dongle inserted before or after connection prompt.

## Expected 

In a perfect world, what do you expect to happen.

should connect

## Operating System and Version

Linux Gallium recent

## GUI Version

5.0.4

Running standalone app

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

## Console Log

Paste any relevant text from the console window here
Screen Resolution: 1920 X 1080
Operating System: Linux
Welcome to the Processing-based OpenBCI GUI!
For more information, please visit: https://openbci.github.io/Documentation/docs/06Software/01-OpenBCISoftware/GUIDocs
OpenBCI_GUI::Setup: GUI v5 Sample Data exists in Documents folder.
ControlP5 2.3.1 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
TopNav: Internet Connection Successful
Local Version: v5.0.4, Latest Version: v5.0.4
GUI is up to date!
OpenBCI_GUI::Control Panel: Playback history file not found.
OpenBCI_GUI::Setup: Setup is complete!
sourceList: click!
Channel count set to 4
[DEFAULT]: BLE Devices Refreshing
ControlPanel: Found BLED112 Dongle on COM port: /dev/ttyACM0
openbci_gui_helpers.GanglionError: Error in scan for ganglions:PORT_OPEN_ERROR
at openbci_gui_helpers.GUIHelper.scan_for_ganglions(GUIHelper.java:69)
at OpenBCI_GUI$BLEBox$1.run(OpenBCI_GUI.java:5260)
[DEFAULT]: BLE Devices Refreshing
ControlPanel: Found BLED112 Dongle on COM port: /dev/ttyACM0
openbci_gui_helpers.GanglionError: Error in scan for ganglions:PORT_OPEN_ERROR
at openbci_gui_helpers.GUIHelper.scan_for_ganglions(GUIHelper.java:69)
at OpenBCI_GUI$BLEBox$1.run(OpenBCI_GUI.java:5260)
[DEFAULT]: BLE Devices Refreshing
ControlPanel: Found BLED112 Dongle on COM port: /dev/ttyACM0
openbci_gui_helpers.GanglionError: Error in scan for ganglions:PORT_OPEN_ERROR
at openbci_gui_helpers.GUIHelper.scan_for_ganglions(GUIHelper.java:69)
at OpenBCI_GUI$BLEBox$1.run(OpenBCI_GUI.java:5260)

**Comment by kenmcneill** [comment]
Apologies, I found the fix for this by adding the user to the dialout group: https://openbci.com/forum/index.php?p=/discussion/597/fixing-linux-write-permission-for-dev-ttyusb0.
